{% set name = "4ti2" %}
{% set version = "1.6.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/4ti2/4ti2/releases/download/Release_{{ version.replace(".", "_") }}/4ti2-{{ version }}.tar.gz
  sha256: f7c191beb14246b643e4fd5b18b53d9966693b9e6d3a569441a0e3ca14b1a86b

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - automake
    - make
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gmp
    - glpk

test:
  commands:
    - gensymm --version

about:
  home: https://4ti2.github.io/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: A software package for algebraic, geometric and combinatorial problems on linear spaces
  doc_url: https://4ti2.github.io/
  dev_url: https://github.com/4ti2/4ti2

extra:
  recipe-maintainers:
    - saraedum
