{% set name = "4ti2" %}
{% set version = "1.6.14" %}
{% set posix = "m2-" if build_platform.startswith("win-") else '' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/4ti2/4ti2/releases/download/Release_{{ version.replace(".", "_") }}/4ti2-{{ version }}.tar.gz
  sha256: 1bc340173f93ca4abd30ea962118bd5057fdedf7e79c71d2a0c4cc9569f8b0b1

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}          # [unix]
    - {{ compiler("cxx") }}        # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - gxx_win-64                   # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}base        # [build_platform.startswith("win-")]
    - {{ posix }}diffutils   # [build_platform.startswith("win-")]
    - {{ posix }}make
  host:
    - gmp
    - glpk

test:
  commands:
    - gensymm --version  # [build_platform == target_platform]

about:
  home: https://4ti2.github.io/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: A software package for algebraic, geometric and combinatorial problems on linear spaces
  doc_url: https://4ti2.github.io/
  dev_url: https://github.com/4ti2/4ti2

extra:
  recipe-maintainers:
    - saraedum
