{% set name = "4ti2" %}
{% set version = "1.6.15" %}
{% set posix = "m2-" if build_platform.startswith("win-") else '' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/4ti2/4ti2/releases/download/Release_{{ version.replace(".", "_") }}/4ti2-{{ version }}.tar.gz
  sha256: 070e639398fda1a4665b3291e5ea80f2ba280d9bffd50656ad8482d471b96965
  patches:
    - 0001-include-ctime-in-Heuristics.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}          # [unix]
    - {{ compiler("cxx") }}        # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ compiler("m2w64_cxx") }}                   # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}base        # [build_platform.startswith("win-")]
    - {{ posix }}diffutils   # [build_platform.startswith("win-")]
    - {{ posix }}make
  host:
    - gmp
    - glpk

test:
  commands:
    - gensymm --version

about:
  home: https://4ti2.github.io/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: A software package for algebraic, geometric and combinatorial problems on linear spaces
  doc_url: https://4ti2.github.io/
  dev_url: https://github.com/4ti2/4ti2

extra:
  recipe-maintainers:
    - saraedum
