travis:
  secure:
    BINSTAR_TOKEN: b+uYL7fcHvpl6eFEKPheyxzmNW+TbGFse9yzPh7MVRn3DgMB1tEBrEt00GrRKu95WNxQhMwBx8xIdY8vf6nd+OC1/7TreQbOfVJgzOh5hagmZs37GeJhyTgnHrTQT8F3vrWXyypv9U8ywWNaLboltUilRrfZus1WinrSH3Z1pTT7A0lvoVcfF2TcazwmQ5sJVbGn2M+OqHnTsclpSDsqXKVV/+jr2M/AusUD43/7zU2mwMyCnMAIp2i6LAPVfDUg/oTR/7uQY4yP7Ej9G/e1LutD9cGlIB4KMKSdm9goQ6ItFQEbNdM2/dePJF+5HpI8YxpYeOIVMBGvYU9hDmcXyO5hNpBR95bO5c4F1t5cwQ/legfyLov7BzYETdA+oSiknIe4cCCxjK6NLPm0qZKpduUIr57gpClTu7pw74s0xyCe9Q4aZGr4oawVx+A/SyxqfRSGsh4Ziu3TXCQhmrfXkK39hERPbHUGg1sb3PxrHGQK8wEVL1+6Fqk/WWyiHjKtHv/QEu4/mHHqxdpn8NY7lBL8wrNzcZmA2L4PZC7sdgoh3fbY5nncl0KYxpzvaRyhU2NZHp/aiFMdFPvv2w4Mio8KXZN/LY/U4MsnKhIox2TrIDFQ8IytUhtsBTpieaa8BktUAZgk9ZLA47Hm9/Z/IzYPsIoFssiQqIK5trCMszI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
